---
sudo: false
dist: bionic
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
  - 'echo injection'
bundler_args: --without system_tests
rvm:
  - 2.5.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_GEM_VERSION="~> 5.0"
matrix:
  fast_finish: true
  include:
    -
      env: DEPLOY_TO_FORGE=yes CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: ouroboros8
  password:
    secure: "VZgR7aikZOw0+TEUT0aOGk/Miq6KifiPohMUQlkSfwirS56Vq0zsMFl/7Qhc5KLzpcg2wIrKVcd0eML1xJfpfFrDOTj6szWgT+6poT12w7CL7En8chalOLydBu7ddy5xSveg2FyuCUBBbWOQaVxGpLZawsWkmz38uTemdgCnb30RKWRAOxv6rbDtJcqTADfz36krklWw20PidwQWsucZCsiZjGHbtdus/kshwsYcfYDFvg4JZNWgpMF3vAvzw9DrWfhAVCdyhRWf2OdiG10jYZQRHyAanqyByQxNdFWoMtNfvcUrjuMhnc9inE/CbHJudM86rrYS5W+Xq5GuObUowCu///TBxXMZAcnJbydz3oC31EMghCzQQghFhwkDD0SlQbQItZajJEef26K3m2KWxFEE+0ZKbuWAHpix9ku5aakuS+Q7tShOd+FOQKZI/s1neX3ah6VIJyB1aD/qrEx19QnQUxCRLhzuLbvbzMCC3r+A8Nf5SotTr7CKAtllDgly2tO4hZwZAn+QTzELPzglZDaLFTBliZQ+5UtWkD4f9BW5DlKSQLNSoMZ8LZwEiOBvXSsYMWpWgt5j0eg4p+CuQRoWqIZufDs4qjSn6Vg/9fkAjkA7i8bJti1gwAcdDPoBIBnBgb2M63NEpicHIAmHFk1tDsuscUzgk8rAgpRJxW4="
  on:
    tags: true
    all_branches: true
    condition: "$DEPLOY_TO_FORGE = yes"
