---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm -f Gemfile.lock
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.4.1
env:
  global:
    - BEAKER_PUPPET_COLLECTION=puppet5 PUPPET_GEM_VERSION="~> 5.0"
matrix:
  fast_finish: true
  include:
    -
      env: CHECK="syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop"
    -
      env: CHECK=parallel_spec
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
branches:
  only:
    - master
    - /^v\d/
notifications:
  email: false
deploy:
  provider: puppetforge
  user: ouroboros8
  password:
    secure: "Scn8EAPbpnG/kpY93BPVLhD7jUgpp/EYRre4nVJompzvaWN6lHb9RUt1t337QFtzSrtfdr8K2XogA9Lm8JKL1jpLoJgvelN37an8fp8MQ0fZWiAhiby8uQW8EW8OmmvHmH4ojx2PTfsAs6pYd3XUS/73YMRYBHaK4FLG4nU02fdyVSykHbvYPuJwh9bCpittN+uDOhS/uKgEn3EHsZrgJuIeKH3a/dNE+k1I9DBkmkh8FLnd4OQnzLxi8BlLUsZJQgCediUyHOJaoC0ddJDb3K+c7VCewO0BSFt3D25wiIoTfm4OluzuFJIYNER/tkB/A9K+oN+Ajc9fSFt7NYMIYI/zpOaPN81KhorpY/lAzohLYkFrNNrv6om3J1Uwnw+jGGPbvLaShropPgv3pmTHRRDT+B2WI782BBH4mb9qsVwX4zvlrzk7KaeLrh/57zbcQJU/xXA3f1tSYcoABb5OXKjtzgQmSowBgw8wU55xzWkBXMhXuzzDh/SON1w07G7CeNfZgBObs3i0ydwMETlF3CVhFm25eutWl8JvrcLCjQ9eEADZHufrxV6/2ya/Hrz+QIdsyaPgUq6DyDkes+LTnJo2/jDrWhmCOVjLckw1f5/5aQp+m489/XcrL3AjUch7FkHfpXSr0KNUU0G6k3WUWfTGSCEc+wc8G6s7Rws85dY="
  on:
    tags: true
    all_branches: true
